# Generated by Django 2.0.2 on 2018-10-31 09:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messagess', '0001_initial'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', '活动参加人'), ('0', '活动发起人')], default='1', max_length=1, verbose_name='报名用户类型')),
                ('username', models.CharField(max_length=20, verbose_name='真实姓名')),
                ('wechat', models.CharField(max_length=20, verbose_name='微信号')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='报名时间')),
            ],
            options={
                'verbose_name': '活动报名记录',
                'verbose_name_plural': '活动报名记录',
            },
        ),
        migrations.CreateModel(
            name='BrowseUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='浏览时间')),
            ],
            options={
                'verbose_name': '用户浏览记录',
                'verbose_name_plural': '用户浏览记录',
            },
        ),
        migrations.CreateModel(
            name='CollectionUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='收藏时间')),
            ],
            options={
                'verbose_name': '用户收藏记录',
                'verbose_name_plural': '用户收藏记录',
            },
        ),
        migrations.CreateModel(
            name='CommentsModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centent', models.TextField(max_length=300, verbose_name='评论内容')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '用户评论记录',
                'verbose_name_plural': '用户评论记录',
            },
        ),
        migrations.CreateModel(
            name='FeedBackModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='反馈标题')),
                ('centent', models.TextField(max_length=300, verbose_name='反馈内容')),
                ('images', models.ImageField(blank=True, null=True, upload_to='FeedBackModels/%y/%d/b93c323b3917482f8fd90396497eed91', verbose_name='反馈图片')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='反馈时间')),
            ],
            options={
                'verbose_name': '用户反馈记录',
                'verbose_name_plural': '用户反馈记录',
            },
        ),
        migrations.CreateModel(
            name='ReporttionUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contion', models.TextField(verbose_name='举报理由')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='举报时间')),
            ],
            options={
                'verbose_name': '用户举报记录',
                'verbose_name_plural': '用户举报记录',
            },
        ),
        migrations.CreateModel(
            name='SharingUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='分享时间')),
            ],
            options={
                'verbose_name': '用户分享记录',
                'verbose_name_plural': '用户分享记录',
            },
        ),
        migrations.CreateModel(
            name='SysMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISOPEN', models.CharField(choices=[('0', '未读'), ('1', '已读')], default='0', max_length=1, verbose_name='是否已读')),
                ('titles', models.CharField(max_length=50, verbose_name='消息标题')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='消息时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityModel', verbose_name='活动')),
                ('sysuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sysuser_messages', to='messagess.SysUserModel', verbose_name='系统用户')),
            ],
            options={
                'verbose_name': '消息内容管理',
                'verbose_name_plural': '消息内容管理',
            },
        ),
    ]
