# Generated by Django 2.0.2 on 2018-10-31 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0002_auto_20181031_1703'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userOperation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysmessages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='接收用户'),
        ),
        migrations.AddField(
            model_name='sharingusermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='分享用户'),
        ),
        migrations.AddField(
            model_name='reporttionusermodel',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityModel', verbose_name='举报活动'),
        ),
        migrations.AddField(
            model_name='reporttionusermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='举报用户'),
        ),
        migrations.AddField(
            model_name='feedbackmodels',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='反馈用户'),
        ),
        migrations.AddField(
            model_name='commentsmodels',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityModel', verbose_name='评论活动'),
        ),
        migrations.AddField(
            model_name='commentsmodels',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_comment', to='userOperation.CommentsModels', verbose_name='父评论'),
        ),
        migrations.AddField(
            model_name='commentsmodels',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户'),
        ),
        migrations.AddField(
            model_name='collectionusermodel',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityModel', verbose_name='收藏活动'),
        ),
        migrations.AddField(
            model_name='collectionusermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收藏用户'),
        ),
        migrations.AddField(
            model_name='browseusermodel',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_db', to='activity.ActivityModel', verbose_name='浏览活动'),
        ),
        migrations.AddField(
            model_name='browseusermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='浏览用户'),
        ),
        migrations.AddField(
            model_name='activityuserinfo',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityModel', verbose_name='活动'),
        ),
        migrations.AddField(
            model_name='activityuserinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='报名用户'),
        ),
    ]
