# Generated by Django 2.0.2 on 2018-10-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userOperation', '0002_auto_20181031_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityuserinfo',
            name='type',
            field=models.CharField(choices=[('0', '活动发起人'), ('1', '活动参加人')], default='1', max_length=1, verbose_name='报名用户类型'),
        ),
        migrations.AlterField(
            model_name='feedbackmodels',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='FeedBackModels/%y/%d/b84f600e7d0e4ca495f4c2618e52bb42', verbose_name='反馈图片'),
        ),
        migrations.AlterField(
            model_name='sysmessages',
            name='ISOPEN',
            field=models.CharField(choices=[('1', '已读'), ('0', '未读')], default='0', max_length=1, verbose_name='是否已读'),
        ),
    ]
