# Generated by Django 2.0.2 on 2018-11-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userOperation', '0003_auto_20181031_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityuserinfo',
            name='type',
            field=models.CharField(choices=[('1', '活动参加人'), ('0', '活动发起人')], default='1', max_length=1, verbose_name='报名用户类型'),
        ),
        migrations.AlterField(
            model_name='feedbackmodels',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='FeedBackModels/%y/%d/6aba045669fb40c3883352a7baefd886', verbose_name='反馈图片'),
        ),
        migrations.AlterField(
            model_name='sysmessages',
            name='ISOPEN',
            field=models.CharField(choices=[('0', '未读'), ('1', '已读')], default='0', max_length=1, verbose_name='是否已读'),
        ),
    ]
