# Generated by Django 2.0.2 on 2018-11-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userOperation', '0005_auto_20181102_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityuserinfo',
            name='type',
            field=models.CharField(choices=[('1', '活动参加人'), ('0', '活动发起人')], default='1', max_length=1, verbose_name='报名用户类型'),
        ),
        migrations.AlterField(
            model_name='feedbackmodels',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='FeedBackModels/%y/%d/7c0e43b3e4624ee1a353f7a6924bb880', verbose_name='反馈图片'),
        ),
        migrations.AlterField(
            model_name='sysmessages',
            name='ISOPEN',
            field=models.CharField(choices=[('1', '已读'), ('0', '未读')], default='0', max_length=1, verbose_name='是否已读'),
        ),
    ]
