# Generated by Django 2.0.2 on 2018-10-31 09:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sysname', models.CharField(max_length=10, verbose_name='系统用户名称')),
                ('sysIntroduction', models.TextField(verbose_name='系统用户简介')),
                ('types', models.CharField(choices=[('0', '消息通知')], default=0, max_length=1, verbose_name='用户类型')),
                ('images', models.ImageField(blank=True, null=True, upload_to='SysUserModel/%Y/%m/adfa63e2a1b141269416de64f666372d', verbose_name='系统用户头像')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '系统用户设置',
                'verbose_name_plural': '系统用户设置',
            },
        ),
        migrations.CreateModel(
            name='SysUserthemenuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themenu_name', models.CharField(max_length=10, verbose_name='菜单名称')),
                ('urls', models.CharField(max_length=255, verbose_name='小程序跳转路径')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('sysuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sysusers', to='messagess.SysUserModel', verbose_name='系统用户')),
            ],
            options={
                'verbose_name': '系统用户菜单',
                'verbose_name_plural': '系统用户菜单',
            },
        ),
    ]
