# Generated by Django 2.0.2 on 2018-11-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagess', '0002_auto_20181031_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysusermodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='SysUserModel/%Y/%m/414570413b9b45e2937f46dba4cd5a16', verbose_name='系统用户头像'),
        ),
    ]
