# Generated by Django 2.0.2 on 2018-11-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagess', '0004_auto_20181102_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysusermodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='SysUserModel/%Y/%m/1558abdc926c4f749f6673f822cd0485', verbose_name='系统用户头像'),
        ),
    ]
