# Generated by Django 2.0.2 on 2018-11-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagess', '0005_auto_20181102_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysusermodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='SysUserModel/%Y/%m/36767173a3fe474d9ecbd5c28d13f5ac', verbose_name='系统用户头像'),
        ),
    ]
