# Generated by Django 2.0.2 on 2018-11-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagess', '0006_auto_20181103_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysusermodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='SysUserModel/%Y/%m/22d73bd3a89a4ec2a04b5da8d29aacae', verbose_name='系统用户头像'),
        ),
    ]
