# Generated by Django 2.0.2 on 2018-10-31 09:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityImagesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ActivityImagesModel/%y/%d/537a7bfcb8204b15b61dce1c096031a3', verbose_name='活动图片')),
                ('indexnum', models.IntegerField(default=0, verbose_name='图片顺序')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '活动图片管理',
                'verbose_name_plural': '活动图片管理',
            },
        ),
        migrations.CreateModel(
            name='ActivityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='Activity/%y/%d/537a7bfcb8204b15b61dce1c096031a3', verbose_name='封面图片')),
                ('title', models.CharField(max_length=50, verbose_name='活动标题')),
                ('content', models.TextField(max_length=500, verbose_name='活动内容')),
                ('startdate', models.DateTimeField(default=datetime.datetime.now, verbose_name='开始时间')),
                ('enddate', models.DateTimeField(default=datetime.datetime.now, verbose_name='结束时间')),
                ('address', models.CharField(max_length=255, verbose_name='活动地点')),
                ('latitude', models.CharField(max_length=200, verbose_name='纬度')),
                ('longitude', models.CharField(max_length=200, verbose_name='经度')),
                ('registration_number', models.IntegerField(default=0, verbose_name='用户报名数')),
                ('limitnum', models.IntegerField(default=10, verbose_name='限制人数')),
                ('username', models.CharField(max_length=3, verbose_name='真实姓名')),
                ('wechat', models.CharField(max_length=20, verbose_name='微信号')),
                ('groupcode', models.ImageField(blank=True, null=True, upload_to='Activity/qr/%y/%d/537a7bfcb8204b15b61dce1c096031a3', verbose_name='群二维码')),
                ('istrue', models.BooleanField(default=False, verbose_name='是否同意协议')),
                ('thedraft', models.BooleanField(default=False, verbose_name='是否发布')),
                ('audit', models.CharField(choices=[('0', '审核中'), ('1', '审核通过')], default=0, max_length=1, verbose_name='审核状态')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '发布活动管理',
                'verbose_name_plural': '发布活动管理',
            },
        ),
        migrations.CreateModel(
            name='ActivityTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类别名称')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='ActivityTypeModel/%y/%d/537a7bfcb8204b15b61dce1c096031a3', verbose_name='类别图片')),
                ('Introduction', models.TextField(max_length=300, verbose_name='类别简介')),
                ('indexnum', models.IntegerField(default=0, verbose_name='排列顺序')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '活动类别管理',
                'verbose_name_plural': '活动类别管理',
            },
        ),
        migrations.CreateModel(
            name='SlideModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='SlideModels/%y/%d/537a7bfcb8204b15b61dce1c096031a3', verbose_name='幻灯片图片')),
                ('indexnum', models.IntegerField(default=0, verbose_name='幻灯片顺序')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityModel', verbose_name='活动')),
            ],
            options={
                'verbose_name': '幻灯片管理',
                'verbose_name_plural': '幻灯片管理',
            },
        ),
        migrations.AddField(
            model_name='activitymodel',
            name='activitytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activitytype', to='activity.ActivityTypeModel', verbose_name='活动类别'),
        ),
    ]
