# Generated by Django 2.0.2 on 2018-11-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20181031_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityimagesmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ActivityImagesModel/%y/%d/775b7a5a172e4115ac7057d1855d8932', verbose_name='活动图片'),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='Activity/%y/%d/775b7a5a172e4115ac7057d1855d8932', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='groupcode',
            field=models.ImageField(blank=True, null=True, upload_to='Activity/qr/%y/%d/775b7a5a172e4115ac7057d1855d8932', verbose_name='群二维码'),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='registration_number',
            field=models.IntegerField(default=1, verbose_name='用户报名数'),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='username',
            field=models.CharField(max_length=20, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='activitytypemodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='ActivityTypeModel/%y/%d/775b7a5a172e4115ac7057d1855d8932', verbose_name='类别图片'),
        ),
        migrations.AlterField(
            model_name='slidemodels',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='SlideModels/%y/%d/775b7a5a172e4115ac7057d1855d8932', verbose_name='幻灯片图片'),
        ),
    ]
