# Generated by Django 2.0.2 on 2018-11-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20181102_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityimagesmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ActivityImagesModel/%y/%d/e2bedbeb369a4119934b9dd6c2fafeb9', verbose_name='活动图片'),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='Activity/%y/%d/e2bedbeb369a4119934b9dd6c2fafeb9', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='enddate',
            field=models.DateTimeField(verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='groupcode',
            field=models.ImageField(blank=True, null=True, upload_to='Activity/qr/%y/%d/e2bedbeb369a4119934b9dd6c2fafeb9', verbose_name='群二维码'),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='startdate',
            field=models.DateTimeField(verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='activitytypemodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='ActivityTypeModel/%y/%d/e2bedbeb369a4119934b9dd6c2fafeb9', verbose_name='类别图片'),
        ),
        migrations.AlterField(
            model_name='slidemodels',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='SlideModels/%y/%d/e2bedbeb369a4119934b9dd6c2fafeb9', verbose_name='幻灯片图片'),
        ),
    ]
