# Generated by Django 2.0.2 on 2018-11-03 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_auto_20181102_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityimagesmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ActivityImagesModel/%y/%d/520812e4edfa43d6b626061defa261a5', verbose_name='活动图片'),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='audit',
            field=models.CharField(choices=[('0', '审核中'), ('1', '审核通过')], default=0, max_length=1, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='Activity/%y/%d/520812e4edfa43d6b626061defa261a5', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='groupcode',
            field=models.ImageField(blank=True, null=True, upload_to='Activity/qr/%y/%d/520812e4edfa43d6b626061defa261a5', verbose_name='群二维码'),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='activitytypemodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='ActivityTypeModel/%y/%d/520812e4edfa43d6b626061defa261a5', verbose_name='类别图片'),
        ),
        migrations.AlterField(
            model_name='slidemodels',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='SlideModels/%y/%d/520812e4edfa43d6b626061defa261a5', verbose_name='幻灯片图片'),
        ),
    ]
