# Generated by Django 2.0.2 on 2018-10-31 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharingSetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_path', models.CharField(choices=[('1', '活动页面'), ('0', '通用页面'), ('2', '发布页面'), ('3', '发现页面'), ('5', '内容页面'), ('4', '消息页面')], default='0', max_length=1, verbose_name='分享页面设置')),
                ('title', models.CharField(max_length=50, verbose_name='分享文字')),
                ('imageUrl', models.ImageField(blank=True, null=True, upload_to='SharingSet/%y/%d/aa0c957fe28b45f296f79f92e9d9a198', verbose_name='分享图片')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '分享页面设置',
                'verbose_name_plural': '分享页面设置',
            },
        ),
    ]
