# Generated by Django 2.0.2 on 2018-11-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharingSet', '0004_auto_20181102_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharingsetmodel',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to='SharingSet/%y/%d/072d5e3fc7eb4351bde22469fba1ce83', verbose_name='分享图片'),
        ),
        migrations.AlterField(
            model_name='sharingsetmodel',
            name='set_path',
            field=models.CharField(choices=[('5', '内容页面'), ('1', '活动页面'), ('2', '发布页面'), ('4', '消息页面'), ('0', '通用页面'), ('3', '发现页面')], default='0', max_length=1, verbose_name='分享页面设置'),
        ),
    ]
