# Generated by Django 2.0.2 on 2018-11-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharingSet', '0005_auto_20181102_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharingsetmodel',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to='SharingSet/%y/%d/47b17ae9897041158643487642979bf4', verbose_name='分享图片'),
        ),
        migrations.AlterField(
            model_name='sharingsetmodel',
            name='set_path',
            field=models.CharField(choices=[('4', '消息页面'), ('0', '通用页面'), ('5', '内容页面'), ('3', '发现页面'), ('2', '发布页面'), ('1', '活动页面')], default='0', max_length=1, verbose_name='分享页面设置'),
        ),
    ]
